apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: firepower
data:
  APP_ENV: "production"
  PLAYBYPLAY_API_BASE_URL: "https://api-web.nhle.com"
  STATS_API_BASE_URL: "https://moneypuck.com"
  MESSAGE_INTERVAL_SECONDS: "60"
  GAME_MAX_DURATION_HOURS: "5"
  SCHEDULER_SHOULD_NOTIFY: "true"
  USE_TASKS_EMULATOR: "true"
  CLOUD_TASKS_EMULATOR_HOST: "cloudtasks:8123"
  HANDLER_HOST: "http://backend:8080"
  GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
  GCP_LOCATION: "${GCP_LOCATION}"
  CLOUD_TASKS_QUEUE: "${CLOUD_TASKS_QUEUE}"
